### ISSUE TITLE
Issues running deploy pipeline

### ISSUE THREAD

**Issue by gbengataylor** [siamaksade/openshift-pipelines-examples#5]
received this error
``` 'invalid input params: param types don't match the user-specified type: [ARGS]'```

The problem was that the ARG param in the openshift-cli task is expecting an array 

Changing the pipeline/deploy-pipeline.yaml resolved the issue. Here is a snippet of the deploy step

```yaml
    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - latest
            - $(params.APP_NAME)
```
